### ISSUE TITLE
Running `cholfact` benchmark leads to `ArgumentError`

### ISSUE THREAD

**Issue by MatthiasJReisinger** [JuliaCI/BaseBenchmarks.jl#19] opened 2016-08-07 20:18 UTC
Hi everyone,

I was trying to run BaseBenchmarks with Julia v0.6 built from the latest commit (ec15da730a5b25431d3cfcdc04e3451a9f3e400e) on branch master and got the following the following error when running running the `cholfact` benchmark:

```
ERROR: ArgumentError: matrix is not symmetric/Hermitian. This error can be avoided by calling cholfact(Hermitian(A)) which will ignore either the upper or lower triangle of the matrix.
```

The code I used to invoke the benchmark was:

```
using BaseBenchmarks
BaseBenchmarks.load!("linalg")
run(BaseBenchmarks.SUITE[["linalg", "factorization", ("cholfact","Matrix",256)]], verbose=true);
```

I'm also using the latest master commit (e7c01ab79de57e05507978c5c69a3cea0a4b58e9) of the BaseBenchmarks repository, so I hope this is not a fault that is caused by my local setup.

Best,
Matthias

**Comment by jrevels** [comment] 2016-08-08 17:38
I can't reproduce this locally, but I think I see the problem. The relevant benchmark definition is [here](https://github.com/JuliaCI/BaseBenchmarks.jl/blob/master/src/linalg/LinAlgBenchmarks.jl#L106), where it the input array in question is generated by

```julia
arr = randmat(s)'  * randmat(s)
```

`randmat` is always seeded such that the values should actually be the same, but there might be some error that's actually causing `arr` to be non-symmetric in a strict sense. This line should be changed to use the `m` defined above:

```julia
m = randmat(s)
arr = m' * m
```

**Comment by jrevels** [comment] 2016-08-08 18:06
Closing this via #20, but feel free to reopen if this didn't resolve the issue on your end.

**Closed by jrevels** 2016-08-08 18:06 UTC
